on:
  schedule:
    # Run every monday at 8 am.
    - cron:  '0 8 * * 1'
name: Old Branch Reminder
jobs:
  remind:
    name: Old Branch Reminder
    runs-on: ubuntu-latest
    steps:
    - name: Old Branch Reminder
      uses: arup-group/action-notify-unused-branches@v5
      with:
        daysOld: 30
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
